#' Create output directory structure
#'
#' \code{CreateRNAOutputStructure} generates the output directories used by
#' \code{\link{RunDESeq2}}, \code{\link{ProcessDEGs}}, 
#' \code{\link{RunDiffBind}}, and \code{\link{ProcessDBRs}}.
#'
#' @param block String or character vector defining the variable(s) to use to
#'   block for unwanted variance, e.g. batch or technical effects.
#' @param level String defining variable of interest.
#' @param base String defining the base output path.
#' @param chip Boolean indicating whether output is being created for ChIP-seq.
#' @return A named List containing the modified base output path and design
#'   formula.
#'
#' @importFrom stats formula
#'
#' @author Jared Andrews
#'
CreateOutputStructure <- function(block, level, base, chip = FALSE) {

  design = NULL
  # Generate folders and craft design.
  if (!is.null(block)) {
    if (!dir.exists(file.path(base, paste0(block, ".Block")))) {
      dir.create(file.path(base, paste0(block, ".Block")))
    }
    if (!chip) {
      design <- formula(paste("~", paste(c(block, level), sep = "",
        collapse = " + ")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block")))) {
      dir.create(file.path(base, paste0(block, ".Block")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/EDAFigures")))) {
      dir.create(file.path(base, paste0(block, ".Block/EDAFigures")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/Robjects")))) {
      dir.create(file.path(base, paste0(block, ".Block/Robjects")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/GeneBoxPlots")))) {
      dir.create(file.path(base, paste0(block, ".Block/GeneBoxPlots")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/MAPlots")))) {
      dir.create(file.path(base, paste0(block, ".Block/MAPlots")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/Heatmaps")))) {
      dir.create(file.path(base, paste0(block, ".Block/Heatmaps")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/DEGFigures")))) {
      dir.create(file.path(base, paste0(block, ".Block/DEGFigures")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/ResultsTables")))) {
      dir.create(file.path(base, paste0(block, ".Block/ResultsTables")))
    }
    if (!dir.exists(file.path(base, paste0(block, ".Block/Enrichments")))) {
      dir.create(file.path(base, paste0(block, ".Block/Enrichments")))
    }
    base <- file.path(base, paste0(block,".Block"))
  } else {
    if (!chip) {
      design <- formula(paste("~", level))
    }
    if (!dir.exists(file.path(base, "NoBlock"))) {
      dir.create(file.path(base, "NoBlock"))
    }
    if (!dir.exists(file.path(base, "NoBlock/EDAFigures"))) {
      dir.create(file.path(base, "NoBlock/EDAFigures"))
    }
    if (!dir.exists(file.path(base, "NoBlock/Robjects"))) {
      dir.create(file.path(base, "NoBlock/Robjects"))
    }
    if (!dir.exists(file.path(base, "NoBlock/GeneBoxPlots"))) {
      dir.create(file.path(base, "NoBlock/GeneBoxPlots"))
    }
    if (!dir.exists(file.path(base, paste0(block, "NoBlock/MAPlots")))) {
      dir.create(file.path(base, paste0(block, "NoBlock/MAPlots")))
    }
    if (!dir.exists(file.path(base, paste0(block, "NoBlock/Heatmaps")))) {
      dir.create(file.path(base, paste0(block, "NoBlock/Heatmaps")))
    }
    if (!dir.exists(file.path(base, "NoBlock/DEGFigures"))) {
      dir.create(file.path(base, "NoBlock/DEGFigures"))
    }
    if (!dir.exists(file.path(base, "NoBlock/ResultsTables"))) {
      dir.create(file.path(base, "NoBlock/ResultsTables"))
    }
    if (!dir.exists(file.path(base, "NoBlock/Enrichments"))) {
      dir.create(file.path(base, "NoBlock/Enrichments"))
    }
    base <- file.path(base, "NoBlock")
  }

  return(list(base = base, design = design))
}


#' Save comparison results
#'
#' \code{SaveRNAResults} saves the results for each comparison in \code{res.list} 
#' along with the gene counts.
#'
#' @param res.list Named List containing \linkS4class{DESeqResults} objects for 
#'   all comparisons generated by \code{\link{ProcessDEGs}}.
#' @param dds A \linkS4class{DESeqDataSet} object as returned by 
#'   \code{\link[DESeq2]{DESeq}}.
#' @param outpath Path to directory to be used for output.
#'
#' @importFrom utils write.table
#' 
#' @export
#'
#' @author Jared Andrews
#'
SaveRNAResults <- function (res.list, dds, outpath) {
  out <- paste0(outpath, "/ResultsTables/")

  write.table(counts(dds, normalized = TRUE), file = paste0(out, 
    "NormalizedGeneCounts.txt"), sep = "\t", quote = FALSE)

  write.table(assay(normTransform(dds)), file = paste0(out, 
    "NormalizedGeneCounts.log2.txt"), sep = "\t", quote = FALSE)

  write.table(fpm(dds), file = paste0(out, "GeneCounts.fpm.txt"), 
    sep = "\t", quote = FALSE)

  for (r in seq_along(res.list)) {
    res <- res.list[r]
    comp <- names(res.list[r])
    resdata <- merge(as.data.frame(res), as.data.frame(counts(dds, 
      normalized = TRUE)), by = "row.names", sort = FALSE)
    names(resdata)[1] <- "Gene"


    write.table(resdata, file = paste0(out, comp, 
      ".Results.NormalizedGeneCounts.txt"), row.names = FALSE, 
      sep = "\t", quote = FALSE)
  }
}
